FROM nvcr.io/nvidia/vllm:26.01-py3

# Install only your own tools or dependencies
RUN apt update && apt install -y git curl

# --- Install ffmpeg for Whisper STT ---
RUN apt update && apt install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Install your app dependencies (but NOT torch or vllm)
COPY /.devcontainer/requirements.txt .
RUN pip install --upgrade pip && \
    pip install -U langchain && \
    pip install -r requirements.txt --no-deps
