FROM python:3.10
FROM nvidia/cuda:13.0.1-devel-ubuntu22.04

# Install ubuntu keyring to avoid apt-get update errors
#RUN apt-get update || true \
    #&& apt-get install -y wget \
    #&& wget http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-keyring/ubuntu-keyring_2023.11.28_all.deb \
    #&& dpkg -i ubuntu-keyring_2023.11.28_all.deb \
    #&& rm ubuntu-keyring_2023.11.28_all.deb


# Install Python + tools
#RUN apt update && apt install -y \
    #python3 \
    #python3-pip \
    #python3-venv \
    #git \
    #curl \
    #&& rm -rf /var/lib/apt/lists/*

#WORKDIR /workspace
#RUN echo "sudo sudoers/dpkg-new select keep" | debconf-set-selections

# Create user lumbini
#RUN useradd -m -s /bin/bash lumbini \
   # && usermod -aG sudo lumbini
# make sudo passwordless
#RUN echo "lumbini ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers


# Install necessary packages
RUN apt update && apt install -y git curl

WORKDIR /workspace
